#:kivy 1.0.9

<AsteroidsBall>:
    size: 50, 50 
    canvas:
        Ellipse:
            pos: self.pos
            size: self.size          

<AsteroidsGame>:

    Label:
        font_size: 50  
        center_x: root.width * 1 / 2
        top: root.top + 5
        text: "Asteroids game"
        
    Label:
        font_size: 70  
        center_x: root.width * 1 / 2
        top: root.top - 50
        text: "0"
    
    AsteroidsBall:
        center: self.parent.center
        